routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    //$arr_ip = geoip()->getLocation('104.114.170.0'); // Chile
    //$arr_ip = geoip()->getLocation('104.73.192.0'); // Mexico
    $arr_ip = geoip()->getLocation(\Request::getClientIp(true)); // Mexico
    if($arr_ip->iso_code === 'MX'){
        return view('mexico.welcome');
    }else if($arr_ip->iso_code === 'CL'){
        return view('chile.welcome');
    }else{
        return view('welcome');
    }
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    Route::resource('roles', 'RoleController');
    Route::resource('users', 'UserController');
    Route::resource('responsibles', 'ResponsibleController');
    Route::post('responsibles/all', 'ResponsibleController@responsibles_all')->name('responsibles.all');
    Route::resource('denominations', 'DenominationController');
    Route::post('denominations/all', 'DenominationController@denominations_all')->name('denominations.all');
    Route::resource('organizations', 'OrganizationController');
    Route::post('organizations/all', 'OrganizationController@organizations_all')->name('organizations.all');
    Route::resource('periods', 'PeriodController');
    Route::post('periods/all', 'PeriodController@periods_all')->name('periods.all');
    Route::resource('beneficiaries', 'BeneficiaryController');
    Route::post('beneficiaries/all', 'BeneficiaryController@beneficiaries_all')->name('beneficiaries.all');
    Route::resource('annexeds', 'AnnexedController');
    Route::post('annexeds/all', 'AnnexedController@annexeds_all')->name('annexeds.all');
    Route::resource('boxes', 'BoxController');
    Route::post('boxes/all', 'BoxController@boxes_all')->name('boxes.all');
    Route::post('department/provinces', 'UbigeoController@department_provinces')->name('department.provinces');
    Route::post('province/districts', 'UbigeoController@province_districts')->name('province.districts');
    Route::post('denomination/organizations', 'AnnexedController@denomination_organizations')->name('denomination.organizations');
    Route::post('organization/annexeds', 'BeneficiaryController@organization_annexeds')->name('organization.annexeds');
    Route::post('organization/annexeds', 'BoxController@organization_annexeds')->name('organization.annexeds');

});

app/Box.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Box extends Model
{
    protected $fillable=[
        'contacto','cajas','emr','lga','nt','gm','l8','cm','p','responsible_id','organization_id','annexed_id', 'period_id'
    ];
}

app/Http/Controllers/BoxController.php
<?php

namespace App\Http\Controllers;

use App\Annexed;
use App\Box;
use App\Organization;
use App\Period;
use App\Responsible;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Session;

class BoxController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function organization_annexeds(Request $request)
    {
        $annexeds = DB::table('annexeds')->where('organization_id', '=', $request->id)
            ->get();
        echo json_encode($annexeds);
    }

    public function index()
    {
        return view('boxes.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $responsibles = Responsible::all();
        $organizations = Organization::join('denominations', 'organizations.denomination_id', 'denominations.id')
            ->select('organizations.id', DB::raw("CONCAT(denominations.nombre,' - ',organizations.nombre) AS nombre"));
        $annexeds = Annexed::all();
        $periods = Period::all();
        return view('boxes.create', ['responsibles' => $responsibles,'organizations' => $organizations,'annexeds' => $annexeds, 'periods' => $periods]);

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate([
            'cajas' => 'required',
        ]);
        $input = $request->all();
        Box::create($input);
        return redirect()->route('boxes.index')->with('success', 'Distribución de cajas registrado correctamente');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $box = DB::table('boxes')
            ->join('responsibles', 'boxes.responsible_id', 'responsibles.id')
            ->join('organizations', 'boxes.organization_id', 'organizations.id')
            ->join('annexeds', 'boxes.annexed_id', 'annexeds.id')
            ->join('periods', 'boxes.period_id', 'periods.id')
            ->select('boxes.*','responsibles.nombre as responsable','organizations.nombre as organizacion','annexeds.nombre as anexo', 'periods.descripcion as periodo')
            ->where('boxes.id', '=', $id)
        ->first();
        return view('boxes.show', ['box' => $box]);

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $responsibles = Responsible::all();
        $periods = Period::all();
        $organizations = Organization::join('denominations', 'organizations.denomination_id', 'denominations.id')
            ->select('organizations.id', DB::raw("CONCAT(denominations.nombre,' - ',organizations.nombre) AS nombre"))->get();
        $box = DB::table('boxes')
            ->join('responsibles', 'boxes.responsible_id', 'responsibles.id')
            ->join('organizations', 'boxes.organization_id', 'organizations.id')
            ->join('annexeds', 'boxes.annexed_id', 'annexeds.id')
            ->join('periods', 'boxes.period_id', 'periods.id')
            ->select('boxes.*','responsibles.nombre as responsable','organizations.nombre as organizacion','annexeds.nombre as anexo', 'periods.descripcion as periodo')
            ->where('boxes.id', '=', $id)
            ->first();
        $annexeds = Annexed::where('annexeds.id',$box>'annexed_id')->get();

        return view('boxes.edit', ['box' => $box, 'responsibles' => $responsibles,'periods' => $periods,'organizations'=>$organizations,'annexeds' => $annexeds]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Box $box)
    {
        $input = $request->all();
        $box->update($input);
        return redirect()->route('boxes.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $box = Box::find($id);
        $box->delete();
        return response()->json(['success' => true]);
    }

    public function boxes_all(Request $request)
    {
        $columns = array(
            0 => 'id',
            1 => 'contacto',
            2 => 'cajas',
            3 => 'emr',
            4 => 'lga',
            5 => 'nt',
            6 => 'gm',
            7 => 'l8',
            8 => 'cm',
            9 => 'p',
            10 => 'organizacion',
            11 => 'anexo',
            12 => 'responsable',
            13 => 'periodo',

        );

        $totalData = Box::count();
        $limit = $request->input('length');
        $start = $request->input('start');
        $order = $columns[$request->input('order.0.column')];
        $dir = $request->input('order.0.dir');

        if (empty($request->input('search.value'))) {
            $search = $request->input('search.value');
            $boxes = DB::table('boxes')
                ->join('responsibles', 'boxes.responsible_id', 'responsibles.id')
                ->join('organizations', 'boxes.organization_id', 'organizations.id')
                ->join('annexeds', 'boxes.annexed_id', 'annexeds.id')
                ->join('periods', 'boxes.period_id', 'periods.id')
                ->select('boxes.*','responsibles.nombre as responsable','organizations.nombre as organizacion','annexeds.nombre as anexo', 'periods.descripcion as periodo')
                ->where('boxes.cajas', 'LIKE', "%{$search}%");
        } else {
            $search = $request->input('search.value');
            $boxes = DB::table('boxes')
                ->join('responsibles', 'boxes.responsible_id', 'responsibles.id')
                ->join('organizations', 'boxes.organization_id', 'organizations.id')
                ->join('annexeds', 'boxes.annexed_id', 'annexeds.id')
                ->join('periods', 'boxes.period_id', 'periods.id')
                ->select('boxes.*','responsibles.nombre as responsable','organizations.nombre as organizacion','annexeds.nombre as anexo', 'periods.descripcion as periodo')
                ->where('boxes.cajas', 'LIKE', "%{$search}%");

        }
        $totalFiltered = $boxes->count();
        $boxes = $boxes->offset($start)
            ->limit($limit)
            ->orderBy($order, $dir)
            ->get();
        $data = array();
        if (!empty($boxes)) {
            foreach ($boxes as $i => $box) {
                $show = route('boxes.show', $box->id);
                $edit = route('boxes.edit', $box->id);
                $destroy = route('boxes.destroy', $box->id);
                $buttons = "<input type='hidden' name='_token' id='csrf-token' value='" . Session::token() . "' />
<a class='btn btn-info btn-sm' href='{$show}'><i
                            class='demo-pli-file-search'></i> Ver</a> ";

                if (Auth::user()->hasPermissionTo('box-edit')) {
                    $buttons = $buttons . "<a class='btn btn-success btn-sm'
                       href='{$edit}'><i class='demo-pli-pencil'></i> Editar</a> ";
                }
                if (Auth::user()->hasPermissionTo('box-delete'))
                {
                    $buttons = $buttons . "<button type='button' class='btn btn-danger btn-sm delete-confirm' data-id='{$box->id}'><i class='demo-pli-trash'></i> Eliminar</button>";
                }

                $roles = '';
                if (!empty(Auth::user()->getRoleNames())) {
                    foreach (Auth::user()->getRoleNames() as $v) {
                        $roles = $roles . '<label class="badge badge-success">' . $v . '</label>';
                    }
                }

                $nestedData['id'] = ($i + 1);
                $nestedData['contacto'] = $box->contacto;
                $nestedData['cajas'] = $box->cajas;
                $nestedData['emr'] = $box->emr;
                $nestedData['lga'] = $box->lga;
                $nestedData['nt'] = $box->nt;
                $nestedData['gm'] = $box->gm;
                $nestedData['l8'] = $box->l8;
                $nestedData['cm'] = $box->cm;
                $nestedData['p'] = $box->p;
                $nestedData['organizacion'] = $box->organizacion;
                $nestedData['anexo'] = $box->anexo;
                $nestedData['responsable'] = $box->responsable;
                $nestedData['periodo'] = $box->periodo;
                $nestedData['options'] = "<div><form action='$destroy' method='POST'>" . $buttons . "</form></div>";
                $data[] = $nestedData;

            }
        }

        $json_data = array(
            "draw" => intval($request->input('draw')),
            "recordsTotal" => intval($totalData),
            "recordsFiltered" => intval($totalFiltered),
            "data" => $data
        );

        echo json_encode($json_data);
    }

}

resources/views/boxes/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="pcoded-content">
        <div class="pcoded-inner-content">

            <div class="main-body">
                <div class="page-wrapper">

                    <div class="page-header">
                        <div class="row align-items-end">
                            <div class="col-lg-8">
                                <div class="page-header-title">
                                    <div class="d-inline">
                                        <h4>Registrar distribución</h4>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-4">
                                <div class="page-header-breadcrumb">
                                    <ul class="breadcrumb-title">
                                        <li class="breadcrumb-item">
                                            <a href="{{ route('home') }}"> <i class="feather icon-home"></i> </a>
                                        </li>
                                        <li class="breadcrumb-item"><a href="{{ route('boxes.index') }}">Distribución
                                                Cajas ONN</a>
                                        </li>
                                        <li class="breadcrumb-item"><a href="#!">Registrar distribución</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="page-body">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="card">
                                    <div class="card-block">
                                        <form class="form-horizontal" id="cajas" method="POST"
                                              action="{{route('boxes.store')}}">
                                            @csrf
                                            <div class="row">
                                                <div class="col-xs-4 col-sm-4 col-md-4">
                                                    <div class="form-group">
                                                        <strong>Iglesia/Organización:</strong>
                                                        {{ Form::select('organization_id', $organizations->pluck('nombre', 'id'), null, array('id' => 'organization_id','class' => 'selectpicker','title'=>'Seleccione...','data-style'=>'form-control','data-width'=>'100%','data-live-search' => 'true', 'required')) }}
                                                    </div>
                                                </div>
                                                <div class="col-xs-4 col-sm-4 col-md-4">
                                                    <div class="form-group">
                                                        <strong>Anexo/Lugar:</strong>
                                                        {{ Form::select('annexed_id', [], null, array('id' => 'annexed_id','class' => 'selectpicker','title'=>'Seleccione...','data-style'=>'form-control','data-width'=>'100%','data-live-search' => 'true')) }}
                                                    </div>
                                                </div>
                                                <div class="col-xs-4 col-sm-4 col-md-4">
                                                    <div class="form-group">
                                                        <strong>Periodo:</strong>
                                                        {{ Form::select('period_id', $periods->pluck('descripcion', 'id'), null, array('id' => 'period_id','class' => 'selectpicker','title'=>'Seleccione...','data-style'=>'form-control','data-width'=>'100%','data-live-search' => 'true', 'required')) }}
                                                    </div>
                                                </div>
                                                <div class="col-xs-4 col-sm-4 col-md-4">
                                                    <div class="form-group">
                                                        <strong>Responsable:</strong>
                                                        {{ Form::select('responsible_id', $responsibles->pluck('nombre', 'id'), null, array('id' => 'responsible_id','class' => 'selectpicker','title'=>'Seleccione...','data-style'=>'form-control','data-width'=>'100%','data-live-search' => 'true', 'required')) }}
                                                    </div>
                                                </div>
                                                <div class="col-xs-4 col-sm-4 col-md-4">
                                                    <div class="form-group">
                                                        <strong>Contacto ONN:</strong>
                                                        {!! Form::text('contacto', null, array('id'=>'contacto','placeholder' => 'Nombres y Apellidos','class' => 'form-control','required')) !!}
                                                    </div>
                                                </div>

                                                <div class="col-xs-4 col-sm-4 col-md-4">
                                                    <div class="form-group">
                                                        <strong>N°Cajas:</strong>
                                                        {!! Form::number('cajas', null, array('id'=>'cjas','placeholder' => 'N° de cajas','class' => 'form-control','required')) !!}
                                                    </div>
                                                </div>
                                                <div class="col-xs-4 col-sm-4 col-md-4">
                                                    <div class="form-group">
                                                        <strong>N° EMR:</strong>
                                                        {!! Form::number('emr', null, array('id'=>'emr','placeholder' => 'N° de libros EMR','class' => 'form-control','required')) !!}
                                                    </div>
                                                </div>
                                                <div class="col-xs-4 col-sm-4 col-md-4">
                                                    <div class="form-group">
                                                        <strong>N° LGA:</strong>
                                                        {!! Form::number('lga', null, array('id'=>'lga','placeholder' => 'N° de libros LGA','class' => 'form-control','required')) !!}
                                                    </div>
                                                </div>
                                                <div class="col-xs-4 col-sm-4 col-md-4">
                                                    <div class="form-group">
                                                        <strong>N° NT:</strong>
                                                        {!! Form::number('nt', null, array('id'=>'nt','placeholder' => 'N° de Nuevo testamento','class' => 'form-control','required')) !!}
                                                    </div>
                                                </div>
                                                <div class="col-xs-4 col-sm-4 col-md-4">
                                                    <div class="form-group">
                                                        <strong>N° GM:</strong>
                                                        {!! Form::number('gm', null, array('id'=>'gm','placeholder' => 'N° de guías del maestro','class' => 'form-control','required')) !!}
                                                    </div>
                                                </div>
                                                <div class="col-xs-4 col-sm-4 col-md-4">
                                                    <div class="form-group">
                                                        <strong>N° L8:</strong>
                                                        {!! Form::number('l8', null, array('id'=>'l8','placeholder' => 'N° de libros lección 8','class' => 'form-control','required')) !!}
                                                    </div>
                                                </div>
                                                <div class="col-xs-4 col-sm-4 col-md-4">
                                                    <div class="form-group">
                                                        <strong>N° CM:</strong>
                                                        {!! Form::number('cm', null, array('id'=>'cm','placeholder' => 'N° de libros CM','class' => 'form-control','required')) !!}
                                                    </div>
                                                </div>
                                                <div class="col-xs-4 col-sm-4 col-md-4">
                                                    <div class="form-group">
                                                        <strong>N° P:</strong>
                                                        {!! Form::number('p', null, array('id'=>'p','placeholder' => 'N° de libros P','class' => 'form-control','required')) !!}
                                                    </div>
                                                </div>
                                                <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                                                    <button type="submit" class="btn btn-primary m-b-0">Guardar
                                                    </button>
                                                    <a href="{{route('boxes.index')}}" type="button"
                                                       class="btn btn-warning" type="reset">Cancelar</a>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
@endsection
@section('js')
    <script type="text/javascript">
        $(document).ready(function () {
            cargar_anexos();

            function cargar_anexos() {
                $('#organization_id').on('change', function () {
                    let id = $(this).val();
                    $.ajaxSetup({
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        }
                    });
                    $.ajax({
                        type: 'POST',
                        url: "{{ route('organization.annexeds') }}",
                        data: {
                            "id": id
                        },
                        dataType: 'JSON',
                        beforeSend: function () {
                        },
                        success: function (data) {
                            let anexos = '';
                            $.each(data, function (i, value) {
                                anexos = anexos + '<option value="' + value['id'] + '">' + value['nombre'] + '</option>';
                            });
                            $('#annexed_id').html(anexos)
                                .selectpicker('refresh');
                        },
                        error: function (err) {
                            console.log(err);
                        }
                    });
                });
            }
        });
    </script>
@endsection

resources/views/boxes/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="pcoded-content">
        <div class="pcoded-inner-content">
            <div class="main-body">
                <div class="page-wrapper">
                    <div class="page-header">
                        <div class="row align-items-end">
                            <div class="col-lg-8">
                                <div class="page-header-title">
                                    <div class="d-inline">
                                        <h4>Detalle distribución de cajas ONN</h4>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-4">
                                <div class="page-header-breadcrumb">
                                    <ul class="breadcrumb-title">
                                        <li class="breadcrumb-item">
                                            <a href="{{ route('home') }}"> <i class="feather icon-home"></i> </a>
                                        </li>
                                        <li class="breadcrumb-item"><a href="{{ route('boxes.index') }}">Distribución cajas ONN</a>
                                        </li>
                                        <li class="breadcrumb-item"><a href="#!">Detalle distribución</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="page-body">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="card">
                                    <div class="card-body">
                                        <div class="col-xs-6 col-sm-6 col-md-6">
                                            <div class="form-group">
                                                <strong><b>Periodo:</b></strong>
                                                {{ $box->periodo }}
                                            </div>
                                        </div>
                                        <div class="col-xs-6 col-sm-6 col-md-6">
                                            <div class="form-group">
                                                <strong><b>Organización:</b></strong>
                                                {{ $box->organizacion }}
                                            </div>
                                        </div>
                                        <div class="col-xs-6 col-sm-6 col-md-6">
                                            <div class="form-group">
                                                <strong><b>Anexo:</b></strong>
                                                {{ $box->anexo }}
                                            </div>
                                        </div>
                                        <div class="col-xs-6 col-sm-6 col-md-6">
                                            <div class="form-group">
                                                <strong><b>Responsable:</b></strong>
                                                {{ $box->responsable }}
                                            </div>
                                        </div>

                                        <div class="col-xs-6 col-sm-6 col-md-6">
                                            <div class="form-group">
                                                <strong><b>Contacto ONN: </b></strong>
                                                {{ $box->contacto }}
                                            </div>
                                        </div>
                                        <div class="col-xs-6 col-sm-6 col-md-6">
                                            <div class="form-group">
                                                <strong><b>N° Cajas: </b></strong>
                                                {{ $box->cajas }}
                                            </div>
                                        </div>
                                        <div class="col-xs-6 col-sm-6 col-md-6">
                                            <div class="form-group">
                                                <strong><b>N° EMR: </b></strong>
                                                {{ $box->emr }}
                                            </div>
                                        </div>
                                        <div class="col-xs-6 col-sm-6 col-md-6">
                                            <div class="form-group">
                                                <strong><b>N° LGA: </b></strong>
                                                {{ $box->lga }}
                                            </div>
                                        </div>
                                        <div class="col-xs-6 col-sm-6 col-md-6">
                                            <div class="form-group">
                                            <strong><b>N° NT:</b></strong>
                                                {{ $box->nt }}
                                            </div>
                                        </div>
                                        <div class="col-xs-6 col-sm-6 col-md-6">
                                            <div class="form-group">
                                                <strong><b>N° GM:</b></strong>
                                                {{ $box->gm }}
                                            </div>
                                        </div>
                                        <div class="col-xs-6 col-sm-6 col-md-6">
                                            <div class="form-group">
                                                <strong><b>N° L8:</b></strong>
                                                {{ $box->l8 }}
                                            </div>
                                        </div>
                                        <div class="col-xs-6 col-sm-6 col-md-6">
                                            <div class="form-group">
                                                <strong><b>N° CM:</b></strong>
                                                {{ $box->cm }}
                                            </div>
                                        </div>
                                        <div class="col-xs-6 col-sm-6 col-md-6">
                                            <div class="form-group">
                                                <strong><b>N° P:</b></strong>
                                                {{ $box->p }}
                                            </div>
                                        </div>
                                        <hr>
                                        <div class="d-flex justify-content-end items-center">
                                            <a href="{{ route('boxes.index') }}"
                                               class="btn btn-success btn-round">
                                                <i class="ti-back-left"></i> Atrás</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection