routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    //$arr_ip = geoip()->getLocation('104.114.170.0'); // Chile
    //$arr_ip = geoip()->getLocation('104.73.192.0'); // Mexico
    $arr_ip = geoip()->getLocation(\Request::getClientIp(true)); // Mexico
    if($arr_ip->iso_code === 'MX'){
        return view('mexico.welcome');
    }else if($arr_ip->iso_code === 'CL'){
        return view('chile.welcome');
    }else{
        return view('welcome');
    }
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    Route::resource('roles', 'RoleController');
    Route::resource('users', 'UserController');
    Route::resource('responsibles', 'ResponsibleController');
    Route::post('responsibles/all', 'ResponsibleController@responsibles_all')->name('responsibles.all');
    Route::resource('denominations', 'DenominationController');
    Route::post('denominations/all', 'DenominationController@denominations_all')->name('denominations.all');
    Route::resource('organizations', 'OrganizationController');
    Route::post('organizations/all', 'OrganizationController@organizations_all')->name('organizations.all');
    Route::resource('periods', 'PeriodController');
    Route::post('periods/all', 'PeriodController@periods_all')->name('periods.all');
    Route::resource('beneficiaries', 'BeneficiaryController');
    Route::post('beneficiaries/all', 'BeneficiaryController@beneficiaries_all')->name('beneficiaries.all');
    Route::resource('annexeds', 'AnnexedController');
    Route::post('annexeds/all', 'AnnexedController@annexeds_all')->name('annexeds.all');
    Route::resource('boxes', 'BoxController');
    Route::post('boxes/all', 'BoxController@boxes_all')->name('boxes.all');
    Route::post('department/provinces', 'UbigeoController@department_provinces')->name('department.provinces');
    Route::post('province/districts', 'UbigeoController@province_districts')->name('province.districts');
    Route::post('denomination/organizations', 'AnnexedController@denomination_organizations')->name('denomination.organizations');
    Route::post('organization/annexeds', 'BeneficiaryController@organization_annexeds')->name('organization.annexeds');
    Route::post('organization/annexeds', 'BoxController@organization_annexeds')->name('organization.annexeds');

});

app/Responsible.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Responsible extends Model
{
    protected $fillable=[
        'nombre'
    ];
}

app/Http/Controllers/ResponsibleController.php
<?php

namespace App\Http\Controllers;

use App\Responsible;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Session;

class ResponsibleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    function __construct()
    {
        $this->middleware('permission:responsible-list');
        $this->middleware('permission:responsible-create', ['only' => ['create', 'store']]);
        $this->middleware('permission:responsible-edit', ['only' => ['edit', 'update']]);
        $this->middleware('permission:responsible-delete', ['only' => ['destroy']]);
    }

    public function index()
    {
        return view('responsibles.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('responsibles.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate([
            'nombre' => 'required|unique:denominations',
        ]);
        $responsibles = $request->all();
        Responsible::create($responsibles);
        return redirect()->route('responsibles.index')->with('success', 'Responsable registrado correctamente');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $responsible = Responsible::find($id);
        return view('responsibles.show', compact('responsible'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $responsible = Responsible::find($id);
        return view('responsibles.edit', ['responsible' => $responsible]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Responsible $responsible)
    {
        request()->validate([
            'nombre' => 'required|unique:responsibles,nombre,'.$responsible->id,
        ]);
        $input = $request->all();
        $responsible->update($input);
        return redirect()->route('responsibles.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $responsible = Responsible::find($id);
        $responsible->delete();
        return response()->json(['success' => true]);
    }

    public function responsibles_all(Request $request)
    {
        $columns = array(
            0 => 'id',
            1 => 'nombre',
        );

        $totalData = Responsible::count();
        $limit = $request->input('length');
        $start = $request->input('start');
        $order = $columns[$request->input('order.0.column')];
        $dir = $request->input('order.0.dir');

        if (empty($request->input('search.value'))) {
            $responsibles = DB::table('responsibles');
        } else {
            $search = $request->input('search.value');

            $responsibles = DB::table('responsibles')
                ->where('$responsibles.nombre', 'LIKE', "%{$search}%");
        }
        $totalFiltered = $responsibles->count();
        $responsibles = $responsibles->offset($start)
            ->limit($limit)
            ->orderBy($order, $dir)
            ->get();
        $data = array();
        if (!empty($responsibles)) {
            foreach ($responsibles as $i => $responsible) {
                $show = route('responsibles.show', $responsible->id);
                $edit = route('responsibles.edit', $responsible->id);
                $destroy = route('responsibles.destroy', $responsible->id);
                $buttons = "<input type='hidden' name='_token' id='csrf-token' value='" . Session::token() . "' />
<a class='btn btn-info btn-sm' href='{$show}'><i
                            class='demo-pli-file-search'></i> Ver</a> ";

                if (Auth::user()->hasPermissionTo('responsible-edit')) {
                    $buttons = $buttons . "<a class='btn btn-success btn-sm'
                       href='{$edit}'><i class='demo-pli-pencil'></i> Editar</a> ";
                }
                if (Auth::user()->hasPermissionTo('responsible-delete')) {
                    $buttons = $buttons . "<button type='button' class='btn btn-danger btn-sm delete-confirm' data-id='{$responsible->id}'><i class='demo-pli-trash'></i> Eliminar</button>";
                }

                $roles = '';
                if (!empty(Auth::user()->getRoleNames())) {
                    foreach (Auth::user()->getRoleNames() as $v) {
                        $roles = $roles . '<label class="badge badge-success">' . $v . '</label>';
                    }
                }

                $nestedData['id'] = ($i + 1);
                $nestedData['nombre'] = $responsible->nombre;
                $nestedData['options'] = "<div><form action='$destroy' method='POST'>" . $buttons . "</form></div>";
                $data[] = $nestedData;

            }
        }

        $json_data = array(
            "draw" => intval($request->input('draw')),
            "recordsTotal" => intval($totalData),
            "recordsFiltered" => intval($totalFiltered),
            "data" => $data
        );

        echo json_encode($json_data);
    }
}

resources/views/responsibles/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="pcoded-content">
        <div class="pcoded-inner-content">
            @if ($errors->any())
                <div class="alert alert-danger">
                    <strong>Whoops!</strong> Hubo algunos problemas con los datos ingresados.<br><br>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <div class="main-body">
                <div class="page-wrapper">

                    <div class="page-header">
                        <div class="row align-items-end">
                            <div class="col-lg-8">
                                <div class="page-header-title">
                                    <div class="d-inline">
                                        <h4>Agregar responsable</h4>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-4">
                                <div class="page-header-breadcrumb">
                                    <ul class="breadcrumb-title">
                                        <li class="breadcrumb-item">
                                            <a href="{{ route('home') }}"> <i class="feather icon-home"></i> </a>
                                        </li>
                                        <li class="breadcrumb-item"><a href="{{ route('responsibles.index') }}">Responsables</a>
                                        </li>
                                        <li class="breadcrumb-item"><a href="#!">Agregar responsable</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="page-body">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="card">
                                    <div class="card-block">
                                        <form class="form-horizontal" id="periodo" method="POST" action="{{route('responsibles.store')}}">
                                            @csrf
                                            <div class="form-group row">
                                                <label class="col-sm-2 col-form-label">Nombres y Apellidos:</label>
                                                <div class="col-sm-10">
                                                    {!! Form::text('nombre', null, array('id'=>'nombre','placeholder' => 'Nombres y Apellidos','class' => 'form-control','required')) !!}
                                                </div>
                                            </div>
                                            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                                                <button type="submit" class="btn btn-primary m-b-0">Guardar</button>
                                                <a href="{{route('responsibles.index')}}" type="button" class="btn btn-warning" type="reset">Cancelar</a>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/responsibles/edit.blade.php
@extends('layouts.app')
@section('content')

    <div class="pcoded-content">
        <div class="pcoded-inner-content">
            <div class="main-body">
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <strong>Whoops!</strong> Hubo algunos problemas con los datos ingresados.<br><br>
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <div class="page-wrapper">
                    <div class="page-header">
                        <div class="row align-items-end">
                            <div class="col-lg-8">
                                <div class="page-header-title">
                                    <div class="d-inline">
                                        <h4>Editar responsable</h4>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-4">
                                <div class="page-header-breadcrumb">
                                    <ul class="breadcrumb-title">
                                        <li class="breadcrumb-item">
                                            <a href="{{ route('home') }}"> <i class="feather icon-home"></i> </a>
                                        </li>
                                        <li class="breadcrumb-item"><a href="{{ route('responsibles.index') }}">Responsables</a>
                                        </li>
                                        <li class="breadcrumb-item"><a href="#!">Editar responsable</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="page-body">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="card">
                                    <div class="card-body">
                                        {!! Form::model($responsible, ['id'=>'responsible','method' => 'PATCH','route' => ['responsibles.update', $responsible->id]]) !!}
                                        <div class="form-group row">
                                            <label class="col-sm-2 col-form-label">Nombres y Apellidos:</label>
                                            <div class="col-sm-10">
                                                {!! Form::text('nombre', null, array('placeholder' => 'Name','class' => 'form-control')) !!}
                                            </div>
                                        </div>
                                        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                                            <button type="submit" class="btn btn-primary m-b-0">Guardar</button>
                                            <a href="{{route('responsibles.index')}}" type="button" class="btn btn-warning"
                                               type="reset">Cancelar</a>
                                        </div>
                                    </div>
                                    {!! Form::close() !!}
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/responsibles/index.blade.php
@extends('layouts.app')

@section('content')
    <!--CONTENT CONTAINER-->
    <!--===================================================-->
    <div class="pcoded-content">
        <div class="pcoded-inner-content">
            <div class="main-body">
                <div class="page-wrapper">
                    <div class="page-header">
                        <div class="row align-items-end">
                            <div class="col-lg-8">
                                <div class="page-header-title">
                                    <div class="d-inline">
                                        <h4>Responsables</h4>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-4">
                                <div class="page-header-breadcrumb">
                                    <ul class="breadcrumb-title">
                                        <li class="breadcrumb-item">
                                            <a href="{{ route('home') }}"> <i class="feather icon-home"></i> </a>
                                        </li>
                                        <li class="breadcrumb-item"><a href="#!">Responsables</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    @if ($message = Session::get('success'))
                        <div class="alert alert-success">
                            <p>{{ $message }}</p>
                        </div>
                    @endif
                    <div class="page-body">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="card">
                                    <div class="card-header">
                                        <div class="pull-right">
                                            <a class="btn btn-success btn-round btn-sm" href="{{ route('responsibles.create') }}"><i
                                                        class="demo-pli-add"></i> Nuevo</a>
                                        </div>
                                    </div>
                                    <div class="card-block">
                                        <div class="dt-responsive table-responsive">
                                            <table id="table"
                                                   class="table table-striped table-bordered nowrap">
                                                <thead>
                                                <tr>
                                                    <th>N°</th>
                                                    <th>Nombre</th>
                                                    <th width="280px">Acciones</th>
                                                </tr>
                                                </thead>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
@endsection
@section('js')
    <script type="text/javascript">
        let tabla = $('#table').DataTable(
            {
                "processing": true,
                "serverSide": true,
                language: {
                    "decimal": "",
                    "emptyTable": "No hay información",
                    "info": "Mostrando _START_ a _END_ de _TOTAL_ Entradas",
                    "infoEmpty": "Mostrando 0 a 0 de 0 Entradas",
                    "infoFiltered": "(Filtrado de _MAX_ total entradas)",
                    "infoPostFix": "",
                    "thousands": ",",
                    "lengthMenu": "Mostrar _MENU_ Entradas",
                    "loadingRecords": "Cargando...",
                    "processing": "Procesando...",
                    "search": "Buscar:",
                    "zeroRecords": "Sin resultados encontrados",
                    "No results matched": "No se encontraron resultados",
                    "paginate": {
                        "first": "Primero",
                        "last": "Ultimo",
                        "next": "Siguiente",
                        "previous": "Anterior"
                    },
                },
                "ajax": {
                    "url": "{{ route('responsibles.all') }}",
                    "dataType": "json",
                    "type": "POST",
                    "data": {
                        _token: "{{csrf_token()}}"
                    }
                },
                "columns": [
                    {"data": "id"},
                    {"data": "nombre"},
                    {"data": "options"}],
                "columnDefs": [
                    {"className": "text-center", "targets": [0,1]},
                    { "bSortable": false, "aTargets": [ 2] },
                ],

            }
        );
        $('#table tbody').on('click', '.delete-confirm', function () {
            let id = $(this).attr('data-id');
            let url = '{!! url('responsibles') !!}/' + id;
            Swal.fire({
                title: '¿Estás seguro?',
                text: "¡No podrás revertir esto!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Si, elimínalo!',
                cancelButtonText: 'Cancelar'
            }).then((result) => {
                if (result.value) {
                    $.ajaxSetup({
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        }
                    });
                    $.ajax({
                        type: 'POST',
                        url: url,
                        data: {
                            "_token": "{{ csrf_token() }}",
                            '_method': 'DELETE',
                        },
                        dataType: 'JSON',
                        beforeSend: function () {
                        },
                        success: function (response) {
                            if (response.success) {
                                Swal.fire(
                                    '¡Correcto!',
                                    'El registro ha sido eliminado.',
                                    'success'
                                );
                                tabla.ajax.reload();
                            } else {
                                Swal.fire(
                                    '¡Incorrecto!',
                                    'Hubo un error al eliminar.',
                                    'error'
                                );
                            }
                        },
                        error: function (err) {
                            console.log(err);
                        }
                    });
                }
            })
        });

    </script>
@endsection

resources/views/responsibles/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="pcoded-content">
        <div class="pcoded-inner-content">
            <div class="main-body">
                <div class="page-wrapper">
                    <div class="page-header">
                        <div class="row align-items-end">
                            <div class="col-lg-8">
                                <div class="page-header-title">
                                    <div class="d-inline">
                                        <h4>Detalle responsable</h4>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-4">
                                <div class="page-header-breadcrumb">
                                    <ul class="breadcrumb-title">
                                        <li class="breadcrumb-item">
                                            <a href="{{ route('home') }}"> <i class="feather icon-home"></i> </a>
                                        </li>
                                        <li class="breadcrumb-item"><a href="{{ route('responsibles.index') }}">Responsables</a>
                                        </li>
                                        <li class="breadcrumb-item"><a href="#!">Detalle responsable</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="page-body">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="card">
                                    <div class="card-body">

                                        <div class="col-xs-6 col-sm-6 col-md-6">
                                            <div class="form-group">
                                                <strong><b>Nombres y Apellidos: </b></strong>
                                                {{ $responsible->nombre }}
                                            </div>
                                        </div>
                                        <hr>
                                        <div class="d-flex justify-content-end items-center">
                                            <a href="{{ route('responsibles.index') }}"
                                               class="btn btn-success btn-round">
                                                <i class="ti-back-left"></i> Atrás</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection