routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    //$arr_ip = geoip()->getLocation('104.114.170.0'); // Chile
    //$arr_ip = geoip()->getLocation('104.73.192.0'); // Mexico
    $arr_ip = geoip()->getLocation(\Request::getClientIp(true)); // Mexico
    if($arr_ip->iso_code === 'MX'){
        return view('mexico.welcome');
    }else if($arr_ip->iso_code === 'CL'){
        return view('chile.welcome');
    }else{
        return view('welcome');
    }
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    Route::resource('roles', 'RoleController');
    Route::resource('users', 'UserController');
    Route::resource('responsibles', 'ResponsibleController');
    Route::post('responsibles/all', 'ResponsibleController@responsibles_all')->name('responsibles.all');
    Route::resource('denominations', 'DenominationController');
    Route::post('denominations/all', 'DenominationController@denominations_all')->name('denominations.all');
    Route::resource('organizations', 'OrganizationController');
    Route::post('organizations/all', 'OrganizationController@organizations_all')->name('organizations.all');
    Route::resource('periods', 'PeriodController');
    Route::post('periods/all', 'PeriodController@periods_all')->name('periods.all');
    Route::resource('beneficiaries', 'BeneficiaryController');
    Route::post('beneficiaries/all', 'BeneficiaryController@beneficiaries_all')->name('beneficiaries.all');
    Route::resource('annexeds', 'AnnexedController');
    Route::post('annexeds/all', 'AnnexedController@annexeds_all')->name('annexeds.all');
    Route::resource('boxes', 'BoxController');
    Route::post('boxes/all', 'BoxController@boxes_all')->name('boxes.all');
    Route::post('department/provinces', 'UbigeoController@department_provinces')->name('department.provinces');
    Route::post('province/districts', 'UbigeoController@province_districts')->name('province.districts');
    Route::post('denomination/organizations', 'AnnexedController@denomination_organizations')->name('denomination.organizations');
    Route::post('organization/annexeds', 'BeneficiaryController@organization_annexeds')->name('organization.annexeds');
    Route::post('organization/annexeds', 'BoxController@organization_annexeds')->name('organization.annexeds');

});

app/Annexed.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Annexed extends Model
{
    protected $fillable=[
        'nombre','telefono','direccion','responsible_id','organization_id'];
}

app/Http/Controllers/AnnexedController.php
<?php

namespace App\Http\Controllers;

use App\Annexed;
use App\Denomination;
use App\Organization;
use App\Responsible;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Session;

class AnnexedController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function denomination_organizations(Request $request)
    {
        $organizations = DB::table('organizations')->where('denomination_id', '=', $request->id)
            ->get();
        echo json_encode($organizations);
    }


    public function index()
    {
        return view('annexeds.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $denominations = Denomination::all();
        $responsibles = Responsible::all();
        return view('annexeds.create', ['denominations' => $denominations,'responsibles' => $responsibles]);

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate([
            'nombre' => 'required|unique:annexeds',
        ]);
        $input = $request->all();
        Annexed::create($input);
        return redirect()->route('annexeds.index')->with('success', 'Anexo registrado correctamente');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $annexed = DB::table('annexeds')
            ->join('responsibles', 'annexeds.responsible_id', 'responsibles.id')
            ->join('organizations', 'annexeds.organization_id', 'organizations.id')
            ->join('denominations', 'organizations.denomination_id', 'denominations.id')
            ->select('annexeds.*','responsibles.nombre as responsable','organizations.nombre as organizacion','denominations.nombre as denominacion')
            ->where('annexeds.id', '=', $id)
            ->first();
        return view('annexeds.show', ['annexed' => $annexed]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $responsibles = Responsible::all();
        $denominations = Denomination::all();
        $annexed = DB::table('annexeds')
            ->join('responsibles', 'annexeds.responsible_id', 'responsibles.id')
            ->join('organizations', 'annexeds.organization_id', 'organizations.id')
            ->join('denominations', 'organizations.denomination_id', 'denominations.id')
            ->select('annexeds.*','responsibles.nombre as responsable','organizations.nombre as organizacion','denominations.nombre as denominacion','denominations.id as denomination_id')
            ->where('annexeds.id', '=', $id)
            ->first();
        $organizations = Organization::where('denomination_id',$annexed->denomination_id)->get();

        return view('annexeds.edit', ['annexed' => $annexed, 'responsibles'=>$responsibles,'organizations'=>$organizations,'denominations'=>$denominations ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  Annexed  $annexed
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Annexed $annexed)
    {
        $input = $request->all();
        $annexed->update($input);
        return redirect()->route('annexeds.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $annexed = Annexed::find($id);
        $annexed->delete();
        return response()->json(['success' => true]);
    }

    public function annexeds_all(Request $request)
    {
        $columns = array(
            0 => 'id',
            1 => 'nombre',
            2 => 'telefono',
            3 => 'direccion',
            4 => 'responsable',
            5 => 'organizacion',
            6 => 'denominacion',

        );

        $totalData = Annexed::count();
        $limit = $request->input('length');
        $start = $request->input('start');
        $order = $columns[$request->input('order.0.column')];
        $dir = $request->input('order.0.dir');

        if (empty($request->input('search.value'))) {
            $search = $request->input('search.value');
            $annexeds = DB::table('annexeds')
                ->join('responsibles', 'annexeds.responsible_id', 'responsibles.id')
                ->join('organizations', 'annexeds.organization_id', 'organizations.id')
                ->join('denominations', 'organizations.denomination_id', 'denominations.id')
                ->select('annexeds.*','responsibles.nombre as responsable','organizations.nombre as organizacion','denominations.nombre as denominacion')
                ->where('annexeds.nombre', 'LIKE', "%{$search}%");
        } else {
            $search = $request->input('search.value');
            $annexeds = DB::table('annexeds')
                ->join('responsibles', 'annexeds.responsible_id', 'responsibles.id')
                ->join('organizations', 'annexeds.organization_id', 'organizations.id')
                ->join('denominations', 'organizations.denomination_id', 'denominations.id')
                ->select('annexeds.*','responsibles.nombre as responsable','organizations.nombre as organizacion','denominations.nombre as denominacion','denominations.nombre as denominacion')
                ->where('annexeds.organizacion', 'LIKE', "%{$search}%");

        }
        $totalFiltered = $annexeds->count();
        $annexeds = $annexeds->offset($start)
            ->limit($limit)
            ->orderBy($order, $dir)
            ->get();
        $data = array();
        if (!empty($annexeds)) {
            foreach ($annexeds as $i => $annexed) {
                $show = route('annexeds.show', $annexed->id);
                $edit = route('annexeds.edit', $annexed->id);
                $destroy = route('annexeds.destroy', $annexed->id);
                $buttons = "<input type='hidden' name='_token' id='csrf-token' value='" . Session::token() . "' />
<a class='btn btn-info btn-sm' href='{$show}'><i
                            class='demo-pli-file-search'></i> Ver</a> ";

                if (Auth::user()->hasPermissionTo('annexed-edit')) {
                    $buttons = $buttons . "<a class='btn btn-success btn-sm'
                       href='{$edit}'><i class='demo-pli-pencil'></i> Editar</a> ";
                }
                if (Auth::user()->hasPermissionTo('annexed-delete')) {
                    $buttons = $buttons . "<button type='button' class='btn btn-danger btn-sm delete-confirm' data-id='{$annexed->id}'><i class='demo-pli-trash'></i> Eliminar</button>";
                }

                $roles = '';
                if (!empty(Auth::user()->getRoleNames())) {
                    foreach (Auth::user()->getRoleNames() as $v) {
                        $roles = $roles . '<label class="badge badge-success">' . $v . '</label>';
                    }
                }

                $nestedData['id'] = ($i + 1);
                $nestedData['nombre'] = $annexed->nombre;
                $nestedData['telefono'] = $annexed->telefono;
                $nestedData['direccion'] = $annexed->direccion;
                $nestedData['responsable'] = $annexed->responsable;
                $nestedData['organizacion'] = $annexed->organizacion;
                $nestedData['denominacion'] = $annexed->denominacion;
                $nestedData['options'] = "<div><form action='$destroy' method='POST'>" . $buttons . "</form></div>";
                $data[] = $nestedData;

            }
        }

        $json_data = array(
            "draw" => intval($request->input('draw')),
            "recordsTotal" => intval($totalData),
            "recordsFiltered" => intval($totalFiltered),
            "data" => $data
        );

        echo json_encode($json_data);
    }


}

resources/views/annexeds/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="pcoded-content">
        <div class="pcoded-inner-content">

            <div class="main-body">
                <div class="page-wrapper">

                    <div class="page-header">
                        <div class="row align-items-end">
                            <div class="col-lg-8">
                                <div class="page-header-title">
                                    <div class="d-inline">
                                        <h4>Agregar anexo</h4>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-4">
                                <div class="page-header-breadcrumb">
                                    <ul class="breadcrumb-title">
                                        <li class="breadcrumb-item">
                                            <a href="{{ route('home') }}"> <i class="feather icon-home"></i> </a>
                                        </li>
                                        <li class="breadcrumb-item"><a href="{{ route('annexeds.index') }}">Anexo</a>
                                        </li>
                                        <li class="breadcrumb-item"><a href="#!">Agregar anexo</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="page-body">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="card">
                                    <div class="card-block">
                                        <form class="form-horizontal" id="anexo" method="POST"
                                              action="{{route('annexeds.store')}}">
                                            @csrf
                                            <div class="row">
                                                <div class="col-xs-4 col-sm-4 col-md-4">
                                                    <div class="form-group">
                                                        <strong>Denominación:</strong>
                                                        {{ Form::select('denomination_id', $denominations->pluck('nombre', 'id'), null, array('id' => 'denomination_id','class' => 'selectpicker','title'=>'Seleccione...','data-style'=>'form-control','data-width'=>'100%','data-live-search' => 'true', 'required')) }}
                                                    </div>
                                                </div>
                                                <div class="col-xs-4 col-sm-4 col-md-4">
                                                    <div class="form-group">
                                                        <strong>Iglesia/Organización:</strong>
                                                        {{ Form::select('organization_id', [], null, array('id' => 'organization_id','class' => 'selectpicker','title'=>'Seleccione...','data-style'=>'form-control','data-width'=>'100%','data-live-search' => 'true', 'required')) }}
                                                    </div>
                                                </div>
                                                <div class="col-xs-4 col-sm-4 col-md-4">
                                                    <div class="form-group">
                                                        <strong>Nombre de Anexo/Lugar:</strong>
                                                        {!! Form::text('nombre', null, array('id'=>'nombre','placeholder' => 'Nombre','class' => 'form-control','required')) !!}
                                                    </div>
                                                </div>
                                                <div class="col-xs-4 col-sm-4 col-md-4">
                                                    <div class="form-group">
                                                        <strong>Responsable:</strong>
                                                        {{ Form::select('responsible_id', $responsibles->pluck('nombre', 'id'), null, array('id' => 'responsible_id','class' => 'selectpicker','title'=>'Seleccione...','data-style'=>'form-control','data-width'=>'100%','data-live-search' => 'true', 'required')) }}
                                                    </div>
                                                </div>
                                                <div class="col-xs-4 col-sm-4 col-md-4">
                                                    <div class="form-group">
                                                        <strong>Teléfono:</strong>
                                                        {!! Form::text('telefono', null, array('id'=>'telefono','placeholder' => 'Teléfono','class' => 'form-control')) !!}
                                                    </div>
                                                </div>
                                                <div class="col-xs-4 col-sm-4 col-md-4">
                                                    <div class="form-group">
                                                        <strong>Dirección:</strong>
                                                        {!! Form::text('direccion', null, array('id'=>'direccion','placeholder' => 'Dirección','class' => 'form-control')) !!}
                                                    </div>
                                                </div>
                                                <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                                                    <button type="submit" class="btn btn-primary m-b-0">Guardar
                                                    </button>
                                                    <a href="{{route('annexeds.index')}}" type="button"
                                                       class="btn btn-warning" type="reset">Cancelar</a>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
@endsection
@section('js')
    <script type="text/javascript">
        $(document).ready(function () {
            cargar_organizacion();

            function cargar_organizacion() {
                $('#denomination_id').on('change', function () {
                    let id = $(this).val();
                    console.log(id)
                    $.ajaxSetup({
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        }
                    });
                    $.ajax({
                        type: 'POST',
                        url: "{{ route('denomination.organizations') }}",
                        data: {
                            "id": id
                        },
                        dataType: 'JSON',
                        beforeSend: function () {
                        },
                        success: function (data) {
                            let organizaciones = '';
                            $.each(data, function (i, value) {
                                organizaciones = organizaciones + '<option value="' + value['id'] + '">' + value['nombre'] + '</option>';
                            });
                            $('#organization_id').html(organizaciones)
                                .selectpicker('refresh');
                        },
                        error: function (err) {
                            console.log(err);
                        }
                    });
                });
            }
        });

    </script>
@endsection

resources/views/annexeds/edit.blade.php
@extends('layouts.app')
@section('content')

    <div class="pcoded-content">
        <div class="pcoded-inner-content">

            <div class="main-body">
                <div class="page-wrapper">

                    <div class="page-header">
                        <div class="row align-items-end">
                            <div class="col-lg-8">
                                <div class="page-header-title">
                                    <div class="d-inline">
                                        <h4>Editar anexo</h4>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-4">
                                <div class="page-header-breadcrumb">
                                    <ul class="breadcrumb-title">
                                        <li class="breadcrumb-item">
                                            <a href="{{ route('home') }}"> <i class="feather icon-home"></i> </a>
                                        </li>
                                        <li class="breadcrumb-item"><a href="{{ route('annexeds.index') }}">Anexos</a>
                                        </li>
                                        <li class="breadcrumb-item"><a href="#!">Editar anexo</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="page-body">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="card">
                                    <div class="card-body">
                                        {!! Form::model($annexed, ['id'=>'anexo','method' => 'PATCH','route' => ['annexeds.update', $annexed->id]]) !!}
                                        <div class="row">
                                            <div class="col-xs-4 col-sm-4 col-md-4">
                                                <div class="form-group">
                                                    <strong>Denominación:</strong>
                                                    {{ Form::select('denomination_id', $denominations->pluck('nombre', 'id'), $annexed->denomination_id, array('id' => 'denomination_id','class' => 'selectpicker','title'=>'Seleccione ...','data-width'=>'100%','data-live-search' => 'true', 'required')) }}
                                                </div>
                                            </div>
                                            <div class="col-xs-4 col-sm-4 col-md-4">
                                                <div class="form-group">
                                                    <strong>Iglesia/Organización:</strong>
                                                    {{ Form::select('organization_id', $organizations->pluck('nombre', 'id'), $annexed->organization_id, array('id' => 'organization_id','class' => 'selectpicker','title'=>'Seleccione ...','data-width'=>'100%','data-live-search' => 'true', 'required')) }}
                                                </div>
                                            </div>
                                            <div class="col-xs-4 col-sm-4 col-md-4">
                                                <div class="form-group">
                                                    <strong>Nombre de Anexo/Lugar:</strong>
                                                    {!! Form::text('nombre', null, array('id'=>'nombre','placeholder' => 'Nombre','class' => 'form-control')) !!}
                                                </div>
                                            </div>
                                            <div class="col-xs-4 col-sm-4 col-md-4">
                                                <div class="form-group">
                                                    <strong>Responsable:</strong>
                                                    {{ Form::select('responsible_id', $responsibles->pluck('nombre', 'id'), $annexed->responsible_id, array('id' => 'responsible_id','class' => 'selectpicker','title'=>'Seleccione ...','data-width'=>'100%','data-live-search' => 'true', 'required')) }}
                                                </div>
                                            </div>
                                            <div class="col-xs-4 col-sm-4 col-md-4">
                                                <div class="form-group">
                                                    <strong>Teléfono:</strong>
                                                    {!! Form::text('telefono', null, array('id'=>'telefono','placeholder' => 'Telefono','class' => 'form-control')) !!}
                                                </div>
                                            </div>
                                            <div class="col-xs-4 col-sm-4 col-md-4">
                                                <div class="form-group">
                                                    <strong>Dirección:</strong>
                                                    {!! Form::text('direccion', null, array('id'=>'direccion','placeholder' => 'Dirección','class' => 'form-control')) !!}
                                                </div>
                                            </div>
                                            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                                                <button type="submit" class="btn btn-primary m-b-0">Guardar
                                                </button>
                                                <a href="{{route('annexeds.index')}}" type="submit"
                                                   class="btn btn-warning" type="reset">Cancelar</a>
                                            </div>
                                        </div>
                                    </div>
                                    {!! Form::close() !!}
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
@endsection
@section('js')
    <script type="text/javascript">
        $(document).ready(function () {
            cargar_organizacion();

            function cargar_organizacion() {
                $('#denomination_id').on('change', function () {
                    let id = $(this).val();
                    console.log(id)
                    $.ajaxSetup({
                        headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                        }
                    });
                    $.ajax({
                        type: 'POST',
                        url: "{{ route('denomination.organizations') }}",
                        data: {
                            "id": id
                        },
                        dataType: 'JSON',
                        beforeSend: function () {
                        },
                        success: function (data) {
                            let organizaciones = '';
                            $.each(data, function (i, value) {
                                organizaciones = organizaciones + '<option value="' + value['id'] + '">' + value['nombre'] + '</option>';
                            });
                            $('#organization_id').html(organizaciones)
                                .selectpicker('refresh');
                        },
                        error: function (err) {
                            console.log(err);
                        }
                    });
                });
            }
        });

    </script>
@endsection